### ISSUE TITLE
hide and show feature with size (breakpoints)

### ISSUE THREAD

**Issue by uxitten** [AnimaApp/Auto-Layout#12]
auto layout best plugin for sketch 
with hide and show feature this plugin complete

**Comment by daneial** [comment]
yes, i agree with @uxitten !
it can huge help to designers!

**Comment by miri-rasoul** [comment]
this feature really needed please to plugin

**Comment by orarbel** [comment]
Coming soon 😁

**Comment by blaskotron** [comment]
Been a year. This would be pretty great to have.

**Comment by cereallarceny** [comment]
@orarbel I've been wanting to create my own plugin to do this for a while.  I figure it may be better to just piggyback off the great work you guys have already done with stacks and grids.

If you're interested and not already working on it - I'd love to implement CSS breakpoints for Anima.  I think it would be totally revolutionary to RWD if designers only had to create one artboard per screen... Enough creating an identical mobile, tablet, and desktop layout for each screen!  It's kinda ridiculous we still do that - no?  😉

I'm a veteran JS developer.  If you're not taking this feature, then I'd love your blessing in doing so myself.  Happy to spec it out with you and your team as well.  Would love your input!

**Comment by orarbel** [comment]
@cereallarceny like this https://docs.animaapp.com/v3/prototype/breakpoints.html ?

**Comment by cereallarceny** [comment]
Actually, that's not what I was intending @orarbel.  This is the great, but it's the same way responsive layouts have always been done in design applications.  I guess what I'm looking for is the ability to create one artboard that you can resize at any time, and it contains all the various components for your design.  One artboard, all your components and links.  Rather than 2... 3... 4+ artboards at various screensizes.  In my opinion, designers shouldn't have to create and maintain that many artboards.  It would be much simpler to create one artboard for every screen in your application or website... not 2-4+ for each screen.
