### ISSUE TITLE
collapsing stacks + nested symbols + center doesn't work

### ISSUE THREAD

**Issue by RaphyRaph** [AnimaApp/Auto-Layout#77]
When collapsing a stack that contains symbols, the centering layout applied to the stack doesn't seem to work. In the screencap below, I would expect the stack to always be centered, regardless how how tall it is.

screencap:
https://www.dropbox.com/s/u8qk2z48c2vefhx/stacking%20and%20centering.mov?dl=0

file:
https://www.dropbox.com/s/dgg16t6jevgija9/stacking%20and%20centering.sketch?dl=0

**Comment by delizade** [comment]
hi @RaphyRaph 

try to group "Stacked Group" in the symbol. I don't know why but grouping is working.

**Comment by tmlarson** [comment]
right there with you.  pretty much everything with autolayout is full of bugs. takes forever to build one component that works momentarily, then you convert it to symbol and it doesnt work at all. literally every aspect of autolayout that used to work is falling apart. tried in both 47.1 and 49.1 with several versions of anima. groups, no groups, etc. I've found avoiding stacks altogether has benefits in that it wont destroy the rest of the pins. I love anima, just frustrated because a lot of work wrecked and hours gone down the drain. :/

**Comment by RaphyRaph** [comment]
I used paddy for stacks now... not perfect, but better supported and doesn't have all the animate and launchpad crap

**Comment by tmlarson** [comment]
I love it thanks guys.

Tyler

**Comment by nicolocampagna** [comment]
Hi Guys, 

I discovered to have this problem right now! :(
Someone knows how to solve it?

Thanks in advance.

**Comment by bazzle** [comment]
Same problem. Seems to me like nested stacks just don't center pin.

**Comment by SimonFricker** [comment]
+1

**Comment by avishic** [comment]
We couldn't reproduce using the new Anima 3 Beta, after some stacks enhancements.
Would you like to try it out and report if resolved?
http://bit.ly/Anima3Beta

**Comment by SimonFricker** [comment]
<img width="404" alt="screenshot 2019-01-24 at 15 36 57" src="https://user-images.githubusercontent.com/5481261/51689133-f5058280-1fed-11e9-9b33-116062c3315b.png">
 thats a big version jump haha

**Comment by bartberden** [comment]
@avishic Still doesn't work properly on Anima 3. Removing the center pin solves the problem.

**Comment by ehaft21** [comment]
Anima 3.1.7 this is not working.  Symbol with stacked elements inside.  Setting some elements within the stack to "none" causes stack to collapse properly, but its parent symbol does not center properly.

**Comment by dlewand691** [comment]
This is still not working in 3.1.9.
